### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by fw3i** [SoloUnity/alfred-Spotify-Commands#1]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/40256755/150686490-68cd97b9-bc93-41a2-814e-0ea61871aec5.png">

My Alfred notification looks like there was something missing in my computer.
Could you tell me which thing should I install so my notification can come back?
It shows normal before I uninstall homebrew......
Thanks!

**Comment by SoloUnity** [comment]
Hi!
This seems as if something went wrong with Alfred. Personally, I would try the following:

1) Try this fix that replaces Alfred notifications with an AppleScript one:

[Spotify Commands for vfanghao.zip](https://github.com/SoloUnity/alfred-Spotify-Commands/files/7923159/Spotify.Commands.for.vfanghao.zip)

2) Reinstalling the workflow

3) Deleting Alfred using something like AppCleaner https://freemacsoft.net/appcleaner/ and then reinstalling it (Of course saving preferences beforehand under advanced > preferences). 

4) Because you deleted homebrew, I suspect that you may have deleted something used by Alfred. In that case, try reinstalling homebrew to see if that fixes the problem. 

Otherwise, because this workflow mostly relies on AppleScript, and assuming all other parts of the workflow is working normally, then I have to say that I can't help much further.

**Comment by SoloUnity** [comment]
> <img alt="image" width="370" src="https://user-images.githubusercontent.com/40256755/150686490-68cd97b9-bc93-41a2-814e-0ea61871aec5.png">
> 
> My Alfred notification looks like there was something missing in my computer. Could you tell me which thing should I install so my notification can come back? It shows normal before I uninstall homebrew...... Thanks!

Hi!
This seems as if something went wrong with Alfred. Personally, I would try the following:

Try this fix that replaces Alfred notifications with an AppleScript one:

[Spotify Commands for vfanghao.zip](https://github.com/SoloUnity/alfred-Spotify-Commands/files/7930755/Spotify.Commands.for.vfanghao.zip)

Reinstalling the workflow

Deleting Alfred using something like AppCleaner https://freemacsoft.net/appcleaner/ and then reinstalling it (Of course saving preferences beforehand under advanced > preferences).

Because you deleted homebrew, I suspect that you may have deleted something used by Alfred. In that case, try reinstalling homebrew to see if that fixes the problem.

Otherwise, because this workflow mostly relies on AppleScript, and assuming all other parts of the workflow is working normally, then I have to say that I can't help much further.

Please let me know if it still doesn't work.

**Comment by fw3i** [comment]
Hi!
Thanks for your help. The new one with AppleScript can work normally.

Still the old one cannot show the notification correctly, I uninstalled Alfred by AppCleaner and reinstalled homebrew and it doesn't fix the problem.

Maybe I should reinstall MacOS when I got time. Anyway, thank you very much!
